// Code generated by ent, DO NOT EDIT.

package fruit

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the fruit type in the database.
	Label = "fruit"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSeason holds the string denoting the season field in the database.
	FieldSeason = "season"
	// Table holds the table name of the fruit in the database.
	Table = "fruits"
)

// Columns holds all SQL columns for fruit fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldSeason,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// SeasonValidator is a validator for the "season" field. It is called by the builders before save.
	SeasonValidator func(string) error
)

// OrderOption defines the ordering options for the Fruit queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// BySeason orders the results by the season field.
func BySeason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeason, opts...).ToFunc()
}
