// Code generated by ent, DO NOT EDIT.

package fruit

import (
	"entgo.io/ent/dialect/sql"
	"github.com/kameshsampath/fruitsgql/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Fruit {
	return predicate.Fruit(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Fruit {
	return predicate.Fruit(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Fruit {
	return predicate.Fruit(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Fruit {
	return predicate.Fruit(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Fruit {
	return predicate.Fruit(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Fruit {
	return predicate.Fruit(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Fruit {
	return predicate.Fruit(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Fruit {
	return predicate.Fruit(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Fruit {
	return predicate.Fruit(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Fruit {
	return predicate.Fruit(sql.FieldEQ(FieldName, v))
}

// Season applies equality check predicate on the "season" field. It's identical to SeasonEQ.
func Season(v string) predicate.Fruit {
	return predicate.Fruit(sql.FieldEQ(FieldSeason, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Fruit {
	return predicate.Fruit(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Fruit {
	return predicate.Fruit(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Fruit {
	return predicate.Fruit(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Fruit {
	return predicate.Fruit(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Fruit {
	return predicate.Fruit(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Fruit {
	return predicate.Fruit(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Fruit {
	return predicate.Fruit(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Fruit {
	return predicate.Fruit(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Fruit {
	return predicate.Fruit(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Fruit {
	return predicate.Fruit(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Fruit {
	return predicate.Fruit(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Fruit {
	return predicate.Fruit(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Fruit {
	return predicate.Fruit(sql.FieldContainsFold(FieldName, v))
}

// SeasonEQ applies the EQ predicate on the "season" field.
func SeasonEQ(v string) predicate.Fruit {
	return predicate.Fruit(sql.FieldEQ(FieldSeason, v))
}

// SeasonNEQ applies the NEQ predicate on the "season" field.
func SeasonNEQ(v string) predicate.Fruit {
	return predicate.Fruit(sql.FieldNEQ(FieldSeason, v))
}

// SeasonIn applies the In predicate on the "season" field.
func SeasonIn(vs ...string) predicate.Fruit {
	return predicate.Fruit(sql.FieldIn(FieldSeason, vs...))
}

// SeasonNotIn applies the NotIn predicate on the "season" field.
func SeasonNotIn(vs ...string) predicate.Fruit {
	return predicate.Fruit(sql.FieldNotIn(FieldSeason, vs...))
}

// SeasonGT applies the GT predicate on the "season" field.
func SeasonGT(v string) predicate.Fruit {
	return predicate.Fruit(sql.FieldGT(FieldSeason, v))
}

// SeasonGTE applies the GTE predicate on the "season" field.
func SeasonGTE(v string) predicate.Fruit {
	return predicate.Fruit(sql.FieldGTE(FieldSeason, v))
}

// SeasonLT applies the LT predicate on the "season" field.
func SeasonLT(v string) predicate.Fruit {
	return predicate.Fruit(sql.FieldLT(FieldSeason, v))
}

// SeasonLTE applies the LTE predicate on the "season" field.
func SeasonLTE(v string) predicate.Fruit {
	return predicate.Fruit(sql.FieldLTE(FieldSeason, v))
}

// SeasonContains applies the Contains predicate on the "season" field.
func SeasonContains(v string) predicate.Fruit {
	return predicate.Fruit(sql.FieldContains(FieldSeason, v))
}

// SeasonHasPrefix applies the HasPrefix predicate on the "season" field.
func SeasonHasPrefix(v string) predicate.Fruit {
	return predicate.Fruit(sql.FieldHasPrefix(FieldSeason, v))
}

// SeasonHasSuffix applies the HasSuffix predicate on the "season" field.
func SeasonHasSuffix(v string) predicate.Fruit {
	return predicate.Fruit(sql.FieldHasSuffix(FieldSeason, v))
}

// SeasonEqualFold applies the EqualFold predicate on the "season" field.
func SeasonEqualFold(v string) predicate.Fruit {
	return predicate.Fruit(sql.FieldEqualFold(FieldSeason, v))
}

// SeasonContainsFold applies the ContainsFold predicate on the "season" field.
func SeasonContainsFold(v string) predicate.Fruit {
	return predicate.Fruit(sql.FieldContainsFold(FieldSeason, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Fruit) predicate.Fruit {
	return predicate.Fruit(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Fruit) predicate.Fruit {
	return predicate.Fruit(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Fruit) predicate.Fruit {
	return predicate.Fruit(func(s *sql.Selector) {
		p(s.Not())
	})
}
