// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// FruitsColumns holds the columns for the "fruits" table.
	FruitsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "season", Type: field.TypeString},
	}
	// FruitsTable holds the schema information for the "fruits" table.
	FruitsTable = &schema.Table{
		Name:       "fruits",
		Columns:    FruitsColumns,
		PrimaryKey: []*schema.Column{FruitsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		FruitsTable,
	}
)

func init() {
}
