// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/kameshsampath/fruitsgql/ent/fruit"
)

// Fruit is the model entity for the Fruit schema.
type Fruit struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Season holds the value of the "season" field.
	Season       string `json:"season,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Fruit) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case fruit.FieldID:
			values[i] = new(sql.NullInt64)
		case fruit.FieldName, fruit.FieldSeason:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Fruit fields.
func (f *Fruit) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case fruit.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			f.ID = int(value.Int64)
		case fruit.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				f.Name = value.String
			}
		case fruit.FieldSeason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field season", values[i])
			} else if value.Valid {
				f.Season = value.String
			}
		default:
			f.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Fruit.
// This includes values selected through modifiers, order, etc.
func (f *Fruit) Value(name string) (ent.Value, error) {
	return f.selectValues.Get(name)
}

// Update returns a builder for updating this Fruit.
// Note that you need to call Fruit.Unwrap() before calling this method if this Fruit
// was returned from a transaction, and the transaction was committed or rolled back.
func (f *Fruit) Update() *FruitUpdateOne {
	return NewFruitClient(f.config).UpdateOne(f)
}

// Unwrap unwraps the Fruit entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (f *Fruit) Unwrap() *Fruit {
	_tx, ok := f.config.driver.(*txDriver)
	if !ok {
		panic("ent: Fruit is not a transactional entity")
	}
	f.config.driver = _tx.drv
	return f
}

// String implements the fmt.Stringer.
func (f *Fruit) String() string {
	var builder strings.Builder
	builder.WriteString("Fruit(")
	builder.WriteString(fmt.Sprintf("id=%v, ", f.ID))
	builder.WriteString("name=")
	builder.WriteString(f.Name)
	builder.WriteString(", ")
	builder.WriteString("season=")
	builder.WriteString(f.Season)
	builder.WriteByte(')')
	return builder.String()
}

// Fruits is a parsable slice of Fruit.
type Fruits []*Fruit
