// Code generated by ent, DO NOT EDIT.

package ent

// CreateFruitInput represents a mutation input for creating fruits.
type CreateFruitInput struct {
	Name   string
	Season string
}

// Mutate applies the CreateFruitInput on the FruitMutation builder.
func (i *CreateFruitInput) Mutate(m *FruitMutation) {
	m.SetName(i.Name)
	m.SetSeason(i.Season)
}

// SetInput applies the change-set in the CreateFruitInput on the FruitCreate builder.
func (c *FruitCreate) SetInput(i CreateFruitInput) *FruitCreate {
	i.Mutate(c.Mutation())
	return c
}
