// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/kameshsampath/fruitsgql/ent/fruit"
	"github.com/kameshsampath/fruitsgql/ent/predicate"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeFruit = "Fruit"
)

// FruitMutation represents an operation that mutates the Fruit nodes in the graph.
type FruitMutation struct {
	config
	op            Op
	typ           string
	id            *int
	name          *string
	season        *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Fruit, error)
	predicates    []predicate.Fruit
}

var _ ent.Mutation = (*FruitMutation)(nil)

// fruitOption allows management of the mutation configuration using functional options.
type fruitOption func(*FruitMutation)

// newFruitMutation creates new mutation for the Fruit entity.
func newFruitMutation(c config, op Op, opts ...fruitOption) *FruitMutation {
	m := &FruitMutation{
		config:        c,
		op:            op,
		typ:           TypeFruit,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withFruitID sets the ID field of the mutation.
func withFruitID(id int) fruitOption {
	return func(m *FruitMutation) {
		var (
			err   error
			once  sync.Once
			value *Fruit
		)
		m.oldValue = func(ctx context.Context) (*Fruit, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Fruit.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withFruit sets the old Fruit of the mutation.
func withFruit(node *Fruit) fruitOption {
	return func(m *FruitMutation) {
		m.oldValue = func(context.Context) (*Fruit, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m FruitMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m FruitMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *FruitMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *FruitMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Fruit.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *FruitMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *FruitMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Fruit entity.
// If the Fruit object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FruitMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *FruitMutation) ResetName() {
	m.name = nil
}

// SetSeason sets the "season" field.
func (m *FruitMutation) SetSeason(s string) {
	m.season = &s
}

// Season returns the value of the "season" field in the mutation.
func (m *FruitMutation) Season() (r string, exists bool) {
	v := m.season
	if v == nil {
		return
	}
	return *v, true
}

// OldSeason returns the old "season" field's value of the Fruit entity.
// If the Fruit object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FruitMutation) OldSeason(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSeason is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSeason requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSeason: %w", err)
	}
	return oldValue.Season, nil
}

// ResetSeason resets all changes to the "season" field.
func (m *FruitMutation) ResetSeason() {
	m.season = nil
}

// Where appends a list predicates to the FruitMutation builder.
func (m *FruitMutation) Where(ps ...predicate.Fruit) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the FruitMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *FruitMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Fruit, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *FruitMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *FruitMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Fruit).
func (m *FruitMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *FruitMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.name != nil {
		fields = append(fields, fruit.FieldName)
	}
	if m.season != nil {
		fields = append(fields, fruit.FieldSeason)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *FruitMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case fruit.FieldName:
		return m.Name()
	case fruit.FieldSeason:
		return m.Season()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *FruitMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case fruit.FieldName:
		return m.OldName(ctx)
	case fruit.FieldSeason:
		return m.OldSeason(ctx)
	}
	return nil, fmt.Errorf("unknown Fruit field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *FruitMutation) SetField(name string, value ent.Value) error {
	switch name {
	case fruit.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case fruit.FieldSeason:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSeason(v)
		return nil
	}
	return fmt.Errorf("unknown Fruit field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *FruitMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *FruitMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *FruitMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Fruit numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *FruitMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *FruitMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *FruitMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Fruit nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *FruitMutation) ResetField(name string) error {
	switch name {
	case fruit.FieldName:
		m.ResetName()
		return nil
	case fruit.FieldSeason:
		m.ResetSeason()
		return nil
	}
	return fmt.Errorf("unknown Fruit field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *FruitMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *FruitMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *FruitMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *FruitMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *FruitMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *FruitMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *FruitMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Fruit unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *FruitMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Fruit edge %s", name)
}
