package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"
	"fmt"

	"github.com/kameshsampath/fruitsgql"
	"github.com/kameshsampath/fruitsgql/ent"
)

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id int) (ent.Noder, error) {
	panic(fmt.Errorf("not implemented: Node - node"))
}

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context, ids []int) ([]ent.Noder, error) {
	panic(fmt.Errorf("not implemented: Nodes - nodes"))
}

// Fruits is the resolver for the fruits field.
func (r *queryResolver) Fruits(ctx context.Context) ([]*ent.Fruit, error) {
	return r.client.Fruit.Query().All(ctx)
}

// Query returns fruitsgql.QueryResolver implementation.
func (r *Resolver) Query() fruitsgql.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
